/*******************************************************************************
 * Copyright (c) 2017 Pegasystems Inc.
 *
 * Contributors:
 *     Manu Varghese
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.16 at 08:26:48 PM GMT 
//


package com.pega.gcs.logviewer.systemscan.hybrid;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HybridHotfix" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="PegaVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HotfixId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SupportRequest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="References" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hybridHotfix"
})
@XmlRootElement(name = "HybridHotfixList")
public class HybridHotfixList {

    @XmlElement(name = "HybridHotfix", required = true)
    protected List<HybridHotfixList.HybridHotfix> hybridHotfix;

    /**
     * Gets the value of the hybridHotfix property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hybridHotfix property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHybridHotfix().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HybridHotfixList.HybridHotfix }
     * 
     * 
     */
    public List<HybridHotfixList.HybridHotfix> getHybridHotfix() {
        if (hybridHotfix == null) {
            hybridHotfix = new ArrayList<HybridHotfixList.HybridHotfix>();
        }
        return this.hybridHotfix;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="PegaVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HotfixId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SupportRequest" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="References" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "pegaVersion",
        "hotfixId",
        "title",
        "supportRequest",
        "references",
        "notes"
    })
    public static class HybridHotfix {

        @XmlElement(name = "Id")
        protected int id;
        @XmlElement(name = "PegaVersion", required = true)
        protected String pegaVersion;
        @XmlElement(name = "HotfixId", required = true)
        protected String hotfixId;
        @XmlElement(name = "Title", required = true)
        protected String title;
        @XmlElement(name = "SupportRequest", required = true)
        protected String supportRequest;
        @XmlElement(name = "References")
        protected String references;
        @XmlElement(name = "Notes")
        protected String notes;

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the pegaVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPegaVersion() {
            return pegaVersion;
        }

        /**
         * Sets the value of the pegaVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPegaVersion(String value) {
            this.pegaVersion = value;
        }

        /**
         * Gets the value of the hotfixId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHotfixId() {
            return hotfixId;
        }

        /**
         * Sets the value of the hotfixId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHotfixId(String value) {
            this.hotfixId = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the supportRequest property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupportRequest() {
            return supportRequest;
        }

        /**
         * Sets the value of the supportRequest property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupportRequest(String value) {
            this.supportRequest = value;
        }

        /**
         * Gets the value of the references property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferences() {
            return references;
        }

        /**
         * Sets the value of the references property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferences(String value) {
            this.references = value;
        }

        /**
         * Gets the value of the notes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotes() {
            return notes;
        }

        /**
         * Sets the value of the notes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotes(String value) {
            this.notes = value;
        }

    }

}
