/*******************************************************************************
 * Copyright (c) 2017 Pegasystems Inc. All rights reserved.
 *
 * Contributors:
 *     Manu Varghese
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.13 at 07:30:34 PM GMT 
//


package com.pega.gcs.logviewer.model.alert;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AlertMessage" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Subcategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Severity" type="{}Severity"/>
 *                   &lt;element name="PDNURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DSSEnableConfig" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DSSEnabled" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DSSThresholdConfig" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DSSValueType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DSSValueUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DSSDefaultValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ChartColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alertMessage"
})
@XmlRootElement(name = "AlertMessageList")
public class AlertMessageList {

    @XmlElement(name = "AlertMessage", required = true)
    protected List<AlertMessageList.AlertMessage> alertMessage;

    /**
     * Gets the value of the alertMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alertMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlertMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlertMessageList.AlertMessage }
     * 
     * 
     */
    public List<AlertMessageList.AlertMessage> getAlertMessage() {
        if (alertMessage == null) {
            alertMessage = new ArrayList<AlertMessageList.AlertMessage>();
        }
        return this.alertMessage;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Subcategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Severity" type="{}Severity"/>
     *         &lt;element name="PDNURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DSSEnableConfig" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DSSEnabled" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DSSThresholdConfig" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DSSValueType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DSSValueUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DSSDefaultValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ChartColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "messageID",
        "category",
        "subcategory",
        "title",
        "severity",
        "pdnurl",
        "description",
        "dssEnableConfig",
        "dssEnabled",
        "dssThresholdConfig",
        "dssValueType",
        "dssValueUnit",
        "dssDefaultValue",
        "chartColor"
    })
    public static class AlertMessage {

        @XmlElement(name = "Id")
        protected int id;
        @XmlElement(name = "MessageID", required = true)
        protected String messageID;
        @XmlElement(name = "Category", required = true)
        protected String category;
        @XmlElement(name = "Subcategory", required = true)
        protected String subcategory;
        @XmlElement(name = "Title", required = true)
        protected String title;
        @XmlElement(name = "Severity", required = true)
        @XmlSchemaType(name = "string")
        protected Severity severity;
        @XmlElement(name = "PDNURL", required = true)
        protected String pdnurl;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "DSSEnableConfig")
        protected String dssEnableConfig;
        @XmlElement(name = "DSSEnabled")
        protected String dssEnabled;
        @XmlElement(name = "DSSThresholdConfig")
        protected String dssThresholdConfig;
        @XmlElement(name = "DSSValueType")
        protected String dssValueType;
        @XmlElement(name = "DSSValueUnit")
        protected String dssValueUnit;
        @XmlElement(name = "DSSDefaultValue")
        protected String dssDefaultValue;
        @XmlElement(name = "ChartColor")
        protected String chartColor;

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the messageID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageID() {
            return messageID;
        }

        /**
         * Sets the value of the messageID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageID(String value) {
            this.messageID = value;
        }

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategory(String value) {
            this.category = value;
        }

        /**
         * Gets the value of the subcategory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubcategory() {
            return subcategory;
        }

        /**
         * Sets the value of the subcategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubcategory(String value) {
            this.subcategory = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the severity property.
         * 
         * @return
         *     possible object is
         *     {@link Severity }
         *     
         */
        public Severity getSeverity() {
            return severity;
        }

        /**
         * Sets the value of the severity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Severity }
         *     
         */
        public void setSeverity(Severity value) {
            this.severity = value;
        }

        /**
         * Gets the value of the pdnurl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPDNURL() {
            return pdnurl;
        }

        /**
         * Sets the value of the pdnurl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPDNURL(String value) {
            this.pdnurl = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the dssEnableConfig property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDSSEnableConfig() {
            return dssEnableConfig;
        }

        /**
         * Sets the value of the dssEnableConfig property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDSSEnableConfig(String value) {
            this.dssEnableConfig = value;
        }

        /**
         * Gets the value of the dssEnabled property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDSSEnabled() {
            return dssEnabled;
        }

        /**
         * Sets the value of the dssEnabled property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDSSEnabled(String value) {
            this.dssEnabled = value;
        }

        /**
         * Gets the value of the dssThresholdConfig property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDSSThresholdConfig() {
            return dssThresholdConfig;
        }

        /**
         * Sets the value of the dssThresholdConfig property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDSSThresholdConfig(String value) {
            this.dssThresholdConfig = value;
        }

        /**
         * Gets the value of the dssValueType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDSSValueType() {
            return dssValueType;
        }

        /**
         * Sets the value of the dssValueType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDSSValueType(String value) {
            this.dssValueType = value;
        }

        /**
         * Gets the value of the dssValueUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDSSValueUnit() {
            return dssValueUnit;
        }

        /**
         * Sets the value of the dssValueUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDSSValueUnit(String value) {
            this.dssValueUnit = value;
        }

        /**
         * Gets the value of the dssDefaultValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDSSDefaultValue() {
            return dssDefaultValue;
        }

        /**
         * Sets the value of the dssDefaultValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDSSDefaultValue(String value) {
            this.dssDefaultValue = value;
        }

        /**
         * Gets the value of the chartColor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChartColor() {
            return chartColor;
        }

        /**
         * Sets the value of the chartColor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChartColor(String value) {
            this.chartColor = value;
        }

    }

}
