/*******************************************************************************
 * Copyright (c) 2017 Pegasystems Inc. All rights reserved.
 *
 * Contributors:
 *     Manu Varghese
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 08:42:57 AM GMT 
//

package com.pega.gcs.logviewer.model.measure;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.pega.gcs.logviewer.model.measure
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.pega.gcs.logviewer.model.measure
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Log4JMeasurePatternList }
	 * 
	 */
	public Log4JMeasurePatternList createLog4JMeasurePatternList() {
		return new Log4JMeasurePatternList();
	}

	/**
	 * Create an instance of
	 * {@link Log4JMeasurePatternList.Log4JMeasurePattern }
	 * 
	 */
	public Log4JMeasurePatternList.Log4JMeasurePattern createLog4JMeasurePatternListLog4JMeasurePattern() {
		return new Log4JMeasurePatternList.Log4JMeasurePattern();
	}

}
